version: "3.8"

services:
  glpi:
    build: .
    container_name: glpi
    ports:
      - "8080:80"  # Acesso ao GLPI na porta 8080
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpiuser
      - MYSQL_PASSWORD=glpipass
    volumes:
      - glpi_files:/var/lib/glpi/files
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-glpi
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpiuser
      MYSQL_PASSWORD: glpipass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  glpi_files:
  mysql_data:
