version: '3.8'

services:
  glpi:
    build: .
    container_name: glpi
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./glpi:/var/www/html
      - ./plugins/singlesignon/singlesignon:/var/www/html/plugins/singlesignon
    environment:
      TZ: America/Sao_Paulo

  db:
    image: mariadb:10.6
    container_name: glpi-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpiuser
      MYSQL_PASSWORD: glpipass
    volumes:
      - glpi_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  glpi_db_data:
